name: run-tests
on:
  push:
    branches:
      - master
  workflow_dispatch: # Manual github trigger (by pressing "Run workflow" on Github "Actions" tab)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test suite (includes pip install)
        run: make test
